version: '3'

services:
  mailhog:
    build: ./docker/mailhog
    ports:
      - "1035:1025"
      - "8025:8025"

  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
#  db:
#    image: postgres
#    restart: always
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./initdb:/docker-entrypoint-initdb.d
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 1234
#      POSTGRES_DB: lsym


###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1234}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
